Exodia/Submit/index.py
Exodia/index.html
layout/styles/custom.css
pages/exodia.html

1. The links of "Problem Statements" on Exodia page were broken.
2. All three events designs were not uniform.
Fixed both of the above issues.

Fixed broken links for exodia

---

index.html
pages/adviser.html
pages/alumni.html
pages/coordinator.html
pages/exodia.html
pages/gallery.html
pages/history.html
pages/vision.html

fixed a problem where exodia page was not appearing on navbar as well…… as made changes to copyright message

Copyright message fix and navbar link fix

---

index.html
layout/scripts/particles.js
layout/styles/layout.css

Modifies the background. its interactive now!

modify background.

---

index.html
layout/styles/layout.css

update footer. icon color. #16

---

index.html
layout/styles/layout.css

Add Mountain vector to banner. Add instagram social icon.

---

index.html

sorry for the inconvenience caused. the file is now added.

Add the mountain svg. #16

---

images/demo/backgrounds/mountain.svg
index.html
layout/scripts/particles.js
layout/scripts/smoothscroll.js
layout/styles/layout.css

modify mountain svg. update 3rd and 4th section. Add a quote section to page. Minor improvements/ fixes. refers to #16
This completes 95% of the homepage. only the banner is left.
preview: http://akshat157.github.io/STAC-IITMandi.github.io

Update the Homepage.

---

index.html
team.html

Center the cards on team page.
Minor fixes.
Run HTML-prettify for code formatting.

Fix team page.

---

layout/styles/layout.css

Noticed that the bug related to the banner text was still there. This commit hopefully fixes it now.

FIX Banner text on mobile devices.

---

activities.html
index.html
team.html
template.html

- activities.html wasn't added to sideNav for mobile devices in index.html and team.html.
- team.html was not added to activities.html sideNav.
- Updated template.html with all these links for later use.
Please keep in mind to update links for both desktop and mobile devices. :slightly_smiling_face:

Correct navBar links.

---

activities.html
layout/styles/layout.css

Reverts STAC-IITMandi/STAC-IITMandi.github.io#57

Revert "fixed zenith logo on activities.html"

---

layout/styles/layout.css

Fix Activities logo

---

activities.html
team.html

This will fix #65.
The activities.html and team.html were not redirecting to home, now they are.

fix: logo at the top-left redirecting to home

---

index.html

fixed unclosed tag,unstructured tag,added missing space.

fixed unclosed tag,unstructured tag

---

index.html

Fix #78  
The footer is now center aligned.

Change Footer alignment

---

index.html

Please review. @shreyasbapat  @akashdakoor  @akshat157

Now instead of read more linking to #, it shows the hidden text. #80

---

index.html

previous link led to 404 . So updated.

updated link to AstraX'20

---

.github/ISSUE_TEMPLATE/Bug_report.md
404.html
CONTRIBUTING.rst
LICENSE
README.md
achievements.html
activities.html
index.html
team.html
template.html
zenith.html

Along with AstraX redirect link update and year update at all places!

Address updates in website

---

404.html
achievements.html
activities.html
index.html
team.html
template.html
zenith.html

Earlier title used to look like `STAC|IIT` now it looks like `STAC | IIT`.

improved look of title

---

404.html
achievements.html
activities.html
index.html
team.html
template.html
zenith.html

Earlier link to [AstraX](https://astrax.in) was broken in sidebar on small devices, now it is updated.

changed link of astrax

---

404.html
achievements.html
activities.html
index.html
team.html
template.html
zenith.html

Now the problem of broken AstraX link is solved.

changed link to astrax in sidebar

---

index.html

I am attaching screenshots.
Old:
New:

improved look of card on main page

---

layout/styles/layout.css

Earlier there was unnecessary smoothscroll.js file in the repository. I removed that added few lines in layout.css. This will help future develops to easily understand the code.

Main-heading on tablet-like devices

---

LICENSE

License Created

---

CONTRIBUTING.md
requirements.txt
src/web_main/settings.py

#133 Switched to Sqlite and updated requirements.txt, contributing guidelines.

Changed database.

---

src/stac_iitmandi/templates/stac_iitmandi/_navbar.html
src/stac_iitmandi/templates/stac_iitmandi/base.html

Navbar  separated into a different file #141

_navbar.html and base.html separated

---

src/stac_iitmandi/templates/stac_iitmandi/base.html
src/stac_iitmandi/templates/stac_iitmandi/footer.html

removed footer from base.html and added into a footer.html file #145

separated footer.html from base.html 

---

src/stac_iitmandi/static/stac_iitmandi/css/style.css
src/stac_iitmandi/templates/stac_iitmandi/_navbar.html
src/stac_iitmandi/templates/stac_iitmandi/base.html
src/stac_iitmandi/views.py

Issue #151 
1. now the current tab is active on which page you are on.
2. added .active tag in style.css 
3. style.css moved to css folder

active page bug fixed 

---

src/manage.py
src/stac_iitmandi/admin.py
src/stac_iitmandi/apps.py
src/stac_iitmandi/migrations/0001_initial.py
src/stac_iitmandi/models.py
src/stac_iitmandi/static/stac_iitmandi/css/style.css
src/stac_iitmandi/static/stac_iitmandi/js/script.js
src/stac_iitmandi/templates/stac_iitmandi/_header.html
src/stac_iitmandi/templates/stac_iitmandi/_navbar.html
src/stac_iitmandi/templates/stac_iitmandi/base.html
src/stac_iitmandi/templates/stac_iitmandi/home.html
src/stac_iitmandi/tests.py
src/stac_iitmandi/urls.py
src/stac_iitmandi/views.py
src/web_main/asgi.py
src/web_main/settings.py
src/web_main/urls.py
src/web_main/wsgi.py

Redo of Home page and layout of website

homepage redo

---

src/stac_iitmandi/static/stac_iitmandi/css/style.css
src/stac_iitmandi/static/stac_iitmandi/js/script.js
src/stac_iitmandi/templates/stac_iitmandi/_header.html
src/stac_iitmandi/templates/stac_iitmandi/_navbar.html

1. Updated navbar button with added animations.
2. Moved all media queries at the end of style.css
3. Adjusted logo size

1. Updated Navbar button 2. Updated css media queries

---

src/stac_iitmandi/static/stac_iitmandi/css/style.css
src/stac_iitmandi/static/stac_iitmandi/js/script.js
src/stac_iitmandi/templates/stac_iitmandi/base.html

Added a scroll top button for going top of the page.

Added Scrolltop Button

---

src/stac_iitmandi/static/stac_iitmandi/css/style.css
src/stac_iitmandi/static/stac_iitmandi/js/script.js
src/stac_iitmandi/templates/stac_iitmandi/alumni.html
src/stac_iitmandi/templates/stac_iitmandi/base.html
src/stac_iitmandi/templates/stac_iitmandi/home.html
src/stac_iitmandi/templates/stac_iitmandi/zenith.html

added carousel

---

src/stac_iitmandi/templates/stac_iitmandi/_navbar.html

1. Fixes #190 
2. Navbar toggler button is now visible in mobile view and left-aligned for common devices
Tested in mobile view of responsive design mode in browser

navbar-toggler alignment to right

---

src/stac_iitmandi/templates/stac_iitmandi/home.html
src/stac_iitmandi/templates/stac_iitmandi/team.html
src/stac_iitmandi/templates/stac_iitmandi/utkarsh.html
src/stac_iitmandi/views.py
src/web_main/settings.py

1. Team page updated.
2.  Updated Utkarsh logo.
Issue #197 , #195

updated team page

---

src/stac_iitmandi/models.py
src/stac_iitmandi/templates/stac_iitmandi/base.html

Added meta tags to add description for the site and async to improve performance of site. Also changed models to decrease size of pictures to be uploaded.
Motivation - https://web.dev/measure/

improved performance

---

requirements.txt
src/stac_iitmandi/templates/stac_iitmandi/_navbar.html
src/stac_iitmandi/templates/stac_iitmandi/iau.html
src/stac_iitmandi/templates/stac_iitmandi/videogallery.html
src/stac_iitmandi/urls.py
src/stac_iitmandi/views.py
src/web_main/settings.py

Added IAU page.
Still need to increase aesthetics and more content

Added IAU page and updated requirements.txt

---

README.md

Added latest information about the repository.

Updated the Readme file with detailed information about the repository.

---

README.md

added instructions to contribute in readmey
